version: '3.7'
services:
  postgres:
    container_name: task-manager-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "devpass"
    volumes:
      - /var/pg_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
  redis:
    container_name: task-manager-redis
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6386:6379"
#  api:
#    container_name: task-manager-api
#    entrypoint: ["bin/goose","-dir","./migrations","postgres","host=localhost port=5432 user=cartips password=$PG_PASSWORD dbname=cartips sslmode=disable","up"]
#    image: go-api
#    restart: always
#    volumes:
#      - type: bind
#        source: ./config.yml
#        target: /config.yml
#    ports:
#      - "8080:8080"