version: '3.7'
services:
  redis:
    container_name: app_redis
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  postgres:
    container_name: app_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "devpass"
    volumes:
      - /var/pg_data:/var/lib/postgresql/data
    networks:
      - task-manager
    ports:
      - "5432:5432"
  api:
    container_name: task-manager-api
    image: app_api
    restart: always
    volumes:
      - type: bind
        source: ./config.yml
        target: /config.yml
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
