version: '3.7'
services:
  api:
    container_name: task-manager-api
    image: app_api
    restart: always
    volumes:
      - type: bind
        source: ./config.yml
        target: /config.yml
    networks:
      - task-manager
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
networks:
  task-manager:
    driver: overlay
    attachable: true
