name: Task-manager-backend-ci

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: appleyboy/ssh-action@master
      with:
        host: 65.108.16.15
        username: lexar
        key: ${{ secrets.OMG_SECRET }}
        port: 22
        script: |
          ls
    - run: pwd
        
#   migrations:
#     runs-on: self-hosted
#     steps:
#     - run: |
#         chmod +x bin/goose
#         bin/goose -dir ./migrations postgres "host=${{secrets.PG_HOST}} port=5432 user=postgres password=${{secrets.PG_PASSWORD}} dbname=postgres sslmode=disable" up
#     needs: 
#     - build
    
#   run:
#     runs-on: self-hosted
#     steps:
#     - run: |
#         echo ${{secrets.CONFIG}} | base64 -d > config.yml
#         docker-compose create
#         docker-compose start
#     needs: 
#     - build
    
#   clear:
#     runs-on: self-hosted
#     steps:
#     - run: docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
#     needs: 
#     - run
